# Generated by Django 3.0.6 on 2021-08-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210824_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(upload_to='Blog/static/image'),
        ),
    ]
